# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: CD

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  register-commands:
    runs-on: ubuntu-latest

    env:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2.0.0

        with:
          deno-version: v2.x

      - name: Debug args
        run: echo "${{ env.APPLICATION_ID }} ${{ env.DISCORD_BOT_TOKEN }}"
        
      - name: Register commands
        run: deno task register-commands --id=${{env.APPLICATION_ID}} --token=${{env.DISCORD_BOT_TOKEN}}
